default: &default
  adapter: postgis
  encoding: unicode
  pool: 10

development:
  private:
    <<: *default
    database: appdb
    username: appuser
    password: app_pass
    host: localhost
    port: 5435
  public:
    <<: *default
    database: analyticsdb
    username: analytics
    password: analytics_pass
    host: localhost
    port: 5436

test:
  private:
    <<: *default
    database: gourmet_private_test
  public:
    <<: *default
    database: gourmet_public_test
